python train.py --model "configs/model/custom0.yaml" --data "configs/data/custom0.yaml" --run_name "sm224-0"
python train.py --model "configs/model/custom1.yaml" --data "configs/data/custom1.yaml" --run_name "sm224-1"
python train.py --model "configs/model/custom2.yaml" --data "configs/data/custom2.yaml" --run_name "sm224-2"
python train.py --model "configs/model/custom3.yaml" --data "configs/data/custom3.yaml" --run_name "sm224-3"
python train.py --model "configs/model/custom4.yaml" --data "configs/data/custom4.yaml" --run_name "sm224-4"