input_channel: 3

depth_multiple: 0.25
width_multiple: 1.0
backbone:
  - - 2
    - Conv
    - - 32
      - 3
      - 2
      - null
      - 1
      - ReLU
  - - 3
    - Conv
    - - 80
      - 1
      - 1
      - null
      - 1
      - LeakyReLU
  - - 1
    - InvertedResidualv3
    - - 3
      - 2.3
      - 32
      - 1
      - 1
      - 1
  - - 4
    - InvertedResidualv2
    - - 56
      - 5
      - 2
  - - 2
    - Conv
    - - 192
      - 5
      - 2
      - null
      - 1
      - SELU
  - - 2
    - InvertedResidualv3
    - - 3
      - 3.7
      - 16
      - 0
      - 0
      - 2
  - - 3
    - MBConv
    - - 1
      - 32
      - 1
      - 3
  - - 1
    - Conv
    - - 1024
      - 1
      - 1
  - - 1
    - GlobalAvgPool
    - []
  - - 1
    - FixedConv
    - - 6
      - 1
      - 1
      - null
      - 1
      - null
