backbone:
- - 2
  - DWConv
  - - 32
    - 3
    - 2
    - null
    - ReLU
- - 2
  - MBConv
  - - 6
    - 16
    - 1
    - 3
- - 2
  - InvertedResidualv3
  - - 3
    - 3.4
    - 64
    - 0
    - 1
    - 2
- - 3
  - InvertedResidualv3
  - - 3
    - 2.3
    - 128
    - 1
    - 1
    - 2
- - 5
  - InvertedResidualv3
  - - 3
    - 1.5
    - 96
    - 0
    - 0
    - 1
- - 1
  - Conv
  - - 896
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - FixedConv
  - - 6
    - 1
    - 1
    - null
    - 1
    - null
depth_multiple: 0.25
input_channel: 3
width_multiple: 1
