backbone:
- - 2
  - DWConv
  - - 32
    - 3
    - 2
    - null
    - ReLU
- - 2
  - MBConv
  - - 6
    - 16
    - 1
    - 3
- - 3
  - DWConv
  - - 48
    - 3
    - 1
    - null
    - ReLU
- - 2
  - InvertedResidualv3
  - - 3
    - 1.6
    - 40
    - 0
    - 1
    - 2
- - 2
  - InvertedResidualv2
  - - 96
    - 1
    - 2
- - 5
  - InvertedResidualv3
  - - 3
    - 2.9
    - 48
    - 0
    - 0
    - 1
- - 1
  - Conv
  - - 768
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - FixedConv
  - - 6
    - 1
    - 1
    - null
    - 1
    - null
depth_multiple: 0.25
input_channel: 3
width_multiple: 1
