input_channel: 3

depth_multiple: 0.25
width_multiple: 0.75

backbone:
    # Example model in PyTorch Tutorial (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
    # [repeat, module, args]
    # Conv [out_channel, kernel_size, stride, padding, groups, activation]
    # DWConv [out_channel, kernel_size, stride, padding, activation]
    # InvertedResidualv2 [c, t, stride]
    # InvertedResidualv3 [kernel, t, c, se, hs, stride]
    [
        [2, Conv, [16, 3, 1, null, 1, 'ReLU']],
        [2, InvertedResidualv3, [5, 1.5, 40, 1, 0, 2]],
        [5, MBConv, [6, 128, 1, 3]],
        [3, DWConv, [192, 3, 2, null, 'Hardswish']],
        [4, DWConv, [512, 3, 1, null, 'ReLU']],
        [1, InvertedResidualv3, [5, 2.6, 32, 0, 1, 1]],
        [1, "Conv", [384, 1, 1]],  # lastdim 바꿔줘야 함
        [1, "GlobalAvgPool", []],
        [1, "FixedConv", [6, 1, 1, null, 1, null]],
    ]
