backbone:
- - 1
  - DWConv
  - - 48
    - 3
    - 1
    - null
    - Hardswish
- - 2
  - InvertedResidualv2
  - - 32
    - 3
    - 2
- - 2
  - DWConv
  - - 64
    - 5
    - 1
    - null
    - Hardswish
- - 2
  - Conv
  - - 224
    - 5
    - 2
    - null
    - 1
    - ReLU
- - 1
  - MBConv
  - - 6
    - 80
    - 1
    - 5
- - 1
  - Conv
  - - 512
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - FixedConv
  - - 6
    - 1
    - 1
    - null
    - 1
    - null
depth_multiple: 0.5
input_channel: 3
width_multiple: 1
