wandb_version: 1

AUG_TEST:
  desc: null
  value: simple_augment_test
AUG_TEST_PARAMS:
  desc: null
  value: null
AUG_TRAIN:
  desc: null
  value: simple_augment_train
AUG_TRAIN_PARAMS:
  desc: null
  value:
    n_select: 4
BATCH_SIZE:
  desc: null
  value: 16
BETA1:
  desc: null
  value: 0.9357227160759888
BETA2:
  desc: null
  value: 0.9746264709276243
DATASET:
  desc: null
  value: TACO
DATA_PATH:
  desc: null
  value: /opt/ml/data
FP16:
  desc: null
  value: true
IMG_SIZE:
  desc: null
  value: 224
INIT_LR:
  desc: null
  value: 0.1
INPUT_SIZE:
  desc: null
  value:
  - 224
  - 224
LR:
  desc: null
  value: 0.0009918728176684841
VAL_RATIO:
  desc: null
  value: 0.8
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1638035992
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      4: 3.8.5
      5: 0.12.7
      8:
      - 5
backbone:
  desc: null
  value:
  - - 2
    - DWConv
    - - 16
      - 3
      - 1
      - null
      - Hardswish
  - - 2
    - Conv
    - - 112
      - 5
      - 2
      - null
      - 1
      - Hardswish
  - - 3
    - InvertedResidualv3
    - - 3
      - 1.0
      - 32
      - 1
      - 0
      - 2
  - - 5
    - MBConv
    - - 6
      - 112
      - 1
      - 5
  - - 2
    - DWConv
    - - 192
      - 3
      - 2
      - null
      - ReLU
  - - 1
    - Conv
    - - 640
      - 1
      - 1
  - - 1
    - GlobalAvgPool
    - []
  - - 1
    - FixedConv
    - - 6
      - 1
      - 1
      - null
      - 1
      - null
depth_multiple:
  desc: null
  value: 0.75
input_channel:
  desc: null
  value: 3
width_multiple:
  desc: null
  value: 0.25
